site_name: ObsidianPublic
nav:
  - Testing formats: Testing formats.md
  - Helicopter money: Resources/Concept of Helicopter money.md
  - Oil price: Resources/Oil price analysis.md

theme:
  name: readthedocs