site_name: YoCreo Ideas
nav:
  - Testing Obsidian contents: Testing Obsidian contents.md
  - Helicopter money: Resources/Concept of Helicopter money.md
  - Oil price: Resources/Oil price analysis.md

theme:
  name: readthedocs